### ISSUE TITLE
[Feature] Add Sponsors section for Prodacity

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#159]
### User Story
**As** a Prodacity sponsor
**I want** to be featured on the event page
**So that** viewers know I'm sponsoring the event

### Acceptance Criteria
**Given** I am viewing the prodacity page
**When** I navigate to the `Sponsored By` section
**Then** I should see a list of event sponsors and their logos
**And** clicking one of the logos should bring me to the sponsor's website

### Notes
- Snyk and Sagely for now and expecting one more
- Make it content driven so non devs can edit it
- Sponsor assets: https://drive.google.com/drive/folders/1PZj7niU9k6HUgWzbnAiVtMzTfG9nNCKU

### Design Mockup
- Snyk press kit: https://snyk.io/press-kit/
- https://www.figma.com/file/KvhZ5amu7Gq2JYU94LHf7p/Rise8-Website?node-id=1681%3A15247

**Comment by josericaurte** [comment]
Attaching PNG logos here so we don't have to go hunting around for them

![clarity-logo](https://user-images.githubusercontent.com/1993330/185942240-2d193643-8ce0-4204-8f3c-9c9b829fbabf.png)
![sagely-logo](https://user-images.githubusercontent.com/1993330/185942243-e2bb273c-6278-4346-a159-0fe3be9b339a.png)
![second-front-systems-logo](https://user-images.githubusercontent.com/1993330/185942244-f2b21301-9288-46cf-a318-c47dffa154f3.png)
![snyk-logo](https://user-images.githubusercontent.com/1993330/185942245-028ef7d4-a0da-4c2e-bfd6-405a32e2cd97.png)
![vmware-logo](https://user-images.githubusercontent.com/1993330/185942246-a783bdd5-cc33-4f58-be6c-ea6136979ac3.png)

**Comment by josericaurte** [comment]
@kivarsson-va Bumped resolution of all logos
![second-front-systems-logo](https://user-images.githubusercontent.com/1993330/185964579-34c95488-67de-4a0d-8215-399d9ca88c52.png)
![sagely-logo](https://user-images.githubusercontent.com/1993330/185964583-15eb5c97-0f2c-4c0f-b997-5cecd3d1e6a6.png)
![clarity-logo](https://user-images.githubusercontent.com/1993330/185964584-fb9290eb-50f9-4e98-901f-8aa2d629c063.png)
![snyk-logo](https://user-images.githubusercontent.com/1993330/185964585-38009f9c-db42-4308-8554-97990bb1cf5f.png)
![vmware-logo](https://user-images.githubusercontent.com/1993330/185964586-217c902c-32a7-43bd-9a76-9f23d7f418a3.png)
s

**Comment by josericaurte** [comment]
@aberner-va Will leave this to you to either re-open or create a new issue!

There was a last minute layout change.


Attached is a screenshot for reference. Changes have been made in the Figma file.

**Desktop**
![Screenshot 2022-08-22 194048](https://user-images.githubusercontent.com/1993330/186038654-febbc30a-1fb6-4536-963a-b82595f39d88.png)

**Mobile**
![Screenshot 2022-08-22 195515](https://user-images.githubusercontent.com/1993330/186039735-3cb48052-fa64-48fc-92de-6f6102cf795a.png)

.
