### ISSUE TITLE
[Feature] Update Footer to match new designs

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#207]
### Acceptance Criteria
**Given** I am viewing any page of the website
**When** I scroll down to the footer
**Then** the footer should match the updated Spark designs
**And** I should be able to edit the footer content

### Design Mockup
-

**Comment by kaivarsson** [comment]
text in the footer is content-driven and the buttons are customizable. right now you can (technically) add as many buttons to the footer as you'd like but it will only display two. depending on the future direction of the website we can iterate on this in the future
