### ISSUE TITLE
[Feature] Refactor Who We Are page section

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#210]
### Acceptance Criteria
**Given** I am viewing the home page
**When** I scroll down to the Who We Are section
**Then** I should see some design tweaks based on the new mockups
**And** I can update the text and images

### Notes
-

### Design Mockup
- https://drive.google.com/drive/folders/1rr0pQAWkhUtObc9ksupyqAvkW3mssUtM

**Comment by kaivarsson** [comment]
this is done but there's an issue with uploading new images in staging. working to resolve it but since the background of this section is content-driven i just had to choose a different image. i was able to upload the motherboard pattern in prod so it is usable there.

will also need to decide on what pictures go in here

**Comment by aberner-va** [comment]
@kaivarsson some observations from my end:
- It looks like there's not as much space above the "who we are" text as there is in the mockup? But I'm also still working off the jpg and not the XD file
- Photos don't overlap like they do in the mock, but this may relate to your above comment. As long as containers are laid out the same
- About us button has a border around the text and arrow vs just around the arrow 

None are a big deal and can be sorted in the design review, just observations

**Comment by kaivarsson** [comment]
@aberner-va 

- yeah, i can add a little more space. like i had mentioned, i'm trying to scale things down proportionally but maybe didn't hit the bullseye on that one
- not related to the aforementioned issue, i didn't use static-sized boxes and instead let the images kinda fill in based on their proportions. if overlapping is a necessity i can adjust it but i also figured it wasn't the most important thing
- also tracking this. again, i'm using a button widget and figured on first pass they could look the same before adding more customizability into the widget

there are some tradeoffs in making all of this content-driven that (IMO) can be refined later. but i can go back and readdress now if you or bryon think it's necessary

**Comment by aberner-va** [comment]
Nah I think it's plenty good for now at least from my perspective. Design review with Kate can pick out any tweaks that need to be made

**Comment by kaivarsson** [comment]
i'm also pushing up the motherboard background as a static asset for now. something is wonky with the uploading of that image in staging, so i'd rather have it in there in case there arises an issue in prod as well before we figure out what it is
