### ISSUE TITLE
[Feature] Refactor Who We Serve section & switch order on page

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#211]
### Acceptance Criteria
**Given** I am viewing the home page
**When** I scroll down to the Who We Serve section
**Then** I should see design tweaks based on the updated prototypes
**And** this section should now come before the Who We Are section

### Notes
- Text and images should be editable

### Design Mockup
-https://drive.google.com/drive/folders/1rr0pQAWkhUtObc9ksupyqAvkW3mssUtM

**Comment by kaivarsson** [comment]
@aberner-va for this one, i made the logos into two rows as discussed with Spark. bryon ultimately wants snap scroll so each section needs to be the height of the screen. that said, i did set the number of items on each row to be content-driven so if in the future we want to change it it shouldn't be difficult

**Comment by aberner-va** [comment]
@kaivarsson makes sense! Is it just staging or are the icons not high enough resolution? They show up a bit pixelated for me

**Comment by kaivarsson** [comment]
@aberner-va those are the ones i found in google drive. they're all content driven so if/when we have better ones we can switch them out
