### ISSUE TITLE
[Feature] Update 3 services sections to match new designs

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#229]
### Acceptance Criteria
**Given** I am viewing the Services page
**When** I scroll down below the big quote section
**Then** I should see the following 3 sections updated to match the new designs:
- Cloud + Platforms
- Pipelines + Pathways
- Applications + Digital Products

### Notes
-

### Design Mockup
- https://drive.google.com/file/d/1qdsCiMDwvTZmAnu38tlg6ZMieCjV20jQ/view?usp=sharing

**Comment by kaivarsson** [comment]
@aberner-va i left out the numbers next to the icons because (IMO) they're just too much. can add if everyone else likes them
