### ISSUE TITLE
[Feature] Rebuild Beliefs in Action section

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#231]
### Acceptance Criteria
**Given** I am viewing the About Us page
**When** I scroll down to the Beliefs in Action section
**Then** I should see the section updated to match the new designs

### Notes
-

### Design Mockup
- https://drive.google.com/drive/folders/1arIqn8sJYXb41oBZETWAC4LUHiQOWHW4

**Comment by kaivarsson** [comment]
@aberner-va with this one, i left the cards styled the way they came out of the box for how i did them in the previous section. i can circle back and add more customizability to them, but i'm thinking i can do that after the rest is done
