### ISSUE TITLE
[Feature] Update Team section of About Us page

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#232]
### Acceptance Criteria
**Given** I am viewing the About Us page
**When** I scroll down to the Future Teammates section
**Then** I should see the section updated to match the new designs

### Notes
-

### Design Mockup
- https://drive.google.com/drive/folders/1arIqn8sJYXb41oBZETWAC4LUHiQOWHW4

**Comment by kaivarsson** [comment]
@aberner-va i'm removing this section from the careers page as well because maintaining the two different sets of styles doesn't make much sense. i can add the new section to the careers page if you'd like
