### ISSUE TITLE
[Feature] Update Core Values section of Careers page

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#245]
### Acceptance Criteria
**Given** I am viewing the Careers page
**When** I scroll down to the Our Core Values section
**Then** it should match the updated designs

### Notes
-

### Design Mockup
- https://drive.google.com/drive/folders/1arIqn8sJYXb41oBZETWAC4LUHiQOWHW4

**Comment by kaivarsson** [comment]
@aberner-va same with this one. used the cards how i had first made them with minimal customizability, will circle back and add more options later

**Comment by aberner-va** [comment]
@kaivarsson In the mockup the text headings on each card are aligned to the top whereas in staging they are aligned to the bottom, so the single line headings appear lower than the multi-line headings

**Comment by kaivarsson** [comment]
@aberner-va yeah tracking a few differences between the design and implementation -- i'm using the same component for the cards across the 3 difference sections with cards and haven't built in much customizability yet, though this specific issue could probably be fixed across all of them. let me know if you want me to address it before or after blogs

**Comment by aberner-va** [comment]
@kaivarsson I think it'd make sense to fix this on all cards and then can add more customization later. Just looks funky having the different line start heights but also fine to get a design second opinion
